name: Issue Comment Events

on:
    issue_comment:
        types: [created, edited]
    issues:
        types: [opened, edited]
    schedule:
        - cron: '*/1  * * * *'

jobs:
    reminder:
        name: Check for reminder
        runs-on: ubuntu-latest

        steps:
            - name: Issue Reminder
              uses: agrc/reminder-action@v1.0.1
