name: 'create reminder'

on:
    issue_comment:
        types: [created, edited]
    issues:
        types: [opened, edited]

jobs:
    reminder:
        runs-on: ubuntu-latest

        steps:
            - name: check for reminder
              uses: agrc/create-reminder-action@v1
